### ISSUE TITLE
Do not prettify in codeblocks option

### ISSUE THREAD

**Issue by araujoarthur** [FlorianWoelki/obsidian-symbols-prettifier#12]
Please, create a toggle to disallow prettifying inside codeblocks. It's really awkward to have a C++ code with field access (->) turning into →, != into ≠, => into ≥ etc...

**Comment by FlorianWoelki** [comment]
This issue is resolved in the [latest version](https://github.com/FlorianWoelki/obsidian-symbols-prettifier/releases/tag/1.2.0).
