### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by merlinuwe** [FlorianWoelki/obsidian-symbols-prettifier#3]
Hm, when I put in these signs in a note

-> 
<-
<->
<=>
<=
=>
?unclear
!important

there is no difference, even when I restart Obsidian.

I don't see the plugin in the list.

![image](https://user-images.githubusercontent.com/4138869/201534418-b3c8f4a0-3a98-45e9-97b0-047c94bce426.png)

Windows 10, latest plugin

**Comment by FlorianWoelki** [comment]
Then maybe you didn't install the plugin? For me, the installation and functionality works fine. What version of obsidian do you use?

**Comment by merlinuwe** [comment]
The trick was to type a blank after the signs ->

Sorry for the confusion. Can you put this in the documentation, please?

**Comment by FlorianWoelki** [comment]
> The trick was to type a blank after the signs ->
> 
> 
> 
> Sorry for the confusion. Can you put this in the documentation, please?
> 
> 
> 
> 

Sure yeah! I'll do this.

**Comment by timothycomeau** [comment]
Installed this plugin today, had the same problem. @FlorianWoelki said he'd put this in the documentation 471 days ago; if it is the documentation it didn't catch my eye.
