### ISSUE TITLE
typing `constructor` inserts HTML and replaces with `undefined`

### ISSUE THREAD

**Issue by michaelbjames** [FlorianWoelki/obsidian-symbols-prettifier#6]
When you type `constructor` and hit space, the following content gets inserted over the word `constructor`.

![image](https://user-images.githubusercontent.com/1889997/235724006-70fd71bd-743c-4a4f-9478-9ead9250f0b6.png)

I would expect the word `constructor` to be unchanged.

btw thanks for making this plugin, it's been very nice to use until hitting this weird bug!

**Comment by sharshuv-quotient** [comment]
I have noticed that too.

**Comment by HanJaeJoon** [comment]
there is another workaround below. I didn't request a PR because it already exists.
https://github.com/HanJaeJoon/obsidian-symbols-prettifier/commit/af6fa452b15e1afd9b9a5bedfc966b36d9bb2208

**Comment by FlorianWoelki** [comment]
Hey sorry for the late reply and thank you for the suggested solutions!

This issue has been fixed in the newest version [v1.1.4](https://github.com/FlorianWoelki/obsidian-symbols-prettifier/releases/tag/1.1.4).
