### ISSUE TITLE
Creates arrows inside inline code block

### ISSUE THREAD

**Issue by Spidermax93** [FlorianWoelki/obsidian-symbols-prettifier#9]
Hi,
Great job on the plugin, I really like what it does.
I only found 1 issue, the arrow is disabled when you are working inside a codeblock delimited by ```.
I then tried it inside an inline code block delimited by ` and it changes the characters => with the arrow.

This will be conflictual with the dataviewJS inline queries.

Would be great to deactivate the changes when you are inline.

Thanks !

**Comment by FlorianWoelki** [comment]
This issue has been resolved with [v1.1.2](https://github.com/FlorianWoelki/obsidian-symbols-prettifier/releases/tag/1.1.2).
